name: RavenCat
favicon: null
layout_spectrum: 0.5736740930005908
typography_spectrum: 0.36304079624824226
title: RavenCat
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7169148279353976
  lightness: 0.8733452372252941
  saturation: 0.45958749228157103
  rhythmicContrast: 0.4580702758394182
purpose: []
